### ISSUE TITLE
Manually trigger GH Action

### ISSUE THREAD

**Issue by roaldarbol** [r-universe/roaldarbol#1]
Hi @jeroen! Sorry to be a bother - I created the repository first, and only created the `packages.json` afterwards, and now I can't seem to manually trigger the GH workflows again to discover the file. Is there any way to do that?

**Comment by jeroen** [comment]
It automatically happens every hour.

**Comment by jeroen** [comment]
However one url in your packages.json does not exist, or it is a private repo. Either way the system can't access it: https://github.com/roaldarbol/pixi

**Comment by roaldarbol** [comment]
Ah, perfect, thanks! (I'd given a different name).

**Comment by roaldarbol** [comment]
By the way, I'm talking a lot with the people over at [prefix.dev](https://prefix.dev/) about making their dependency-management tool, [pixi](https://pixi.sh/), better suited to R (pixi is cross-platform, and aimed at being multi-language/language agnostic). One thing we've been discussing is that it could be possible to build conda packages automatically from the metadata at r-universe. There's been 2 ideas up: 1) They use the metadata to generate recipes and build conda-packages as a separate database, or 2) we could generate recipes and build the packages as part of the r-universe workflow - this would of course require some work on the r-universe side, but I could imagine they could help with it. Would you be interested in taking part in conversation about it?  Most of the discussion goes on at their discord server.
